language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: copernicus-cmems
  password:
    secure: UstSFk7rzdG8W1PXE8aStzB/AeRaGTVFZAAXj2u6eTfionZzykkvT+KzVNlR+qc7/WRpRnZ2iVHy9QrhAoD2uP5cBBLwI8JDA0W5CjZc746uG460e2oSQH68O2KUO6GzTZRCYbLFghcdpOXNij74wOJsPt5dy1kHAG/rlsXFpWO8S2oQrvuCvlHKIfKvO5Um/wqS5b8D5/d1YxHyNqhRHzFKEpUGFa6zQVwI4UCAizTu4vG0ADFHkwq43IJR6YdVl5DHNPAUoL3t48HQjYXC9TcxsrkhZGlzl7RpXRkLOHxNe/hLcd3cPm6pMVQaZTZYX5nQcA/UF+UPStDLEcueJL5H6DZCIJAC8VQ8lkRHwXXjr3usaDMhNIIjVHGXpFgfYDTqMGKI7ZlLBkWr5lgr7sQZXShuLubudHMolQOZGpL1Mm3tLagcmyonhudaxN9ouraz1gZ0QnywXoeJu+MWAnD6gY4GEBQcfkRneENTUS1a1CPH3qyPD8XaibCCi61AXHqjXBoPwEGaIJbZutncuPV7t1AH+dl18rQHzhOu1h3w3teg5Z02VR9faII4MVkQVHfrIGq/1OgRF9tkrywtRMI2kbp5SA1g8DJDQgq0aD9evP6yizw7Z11NsNkD4MyKTuGXEVIXNKPr/ac8nWJjjEPUYYTkD5K+FE3c7oaIv0g=
  on:
    tags: true
    repo: copernicusmarine/cmemsapi
    python: 3.8
