language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: copernicus-cmems
  password: ${pypi_password}
  on:
    tags: true
    branch:
      - master
    repo: copernicusmarine/cmemsapi
    python: 3.7
